AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI4NG EEG Upload Lambda API

Parameters:
  SharedApiId:
    Type: String
    Description: "API Gateway ID exported from shared API stack"

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: dotnet8

Resources:
  # S3 Bucket
  EEGUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ai4ngstore-dev
      VersioningConfiguration:
        Status: Enabled

  # Lambda Function: EEG Upload
  AI4NGUploadLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: AI4NGUploadLambda::AI4NGUploadLambda.Function::FunctionHandler
      CodeUri: ../src/AI4NGUploadLambda
      Environment:
        Variables:
          UPLOAD_BUCKET: !Ref EEGUploadBucket
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3WritePolicy:
            BucketName: !Ref EEGUploadBucket
      Events:
        GeneratePresignedUrl:
          Type: HttpApi
          Properties:
            Path: /api/upload
            Method: GET
            ApiId: REPLACE_WITH_API_ID
            Auth:
              Authorizer: CognitoAuthorizer

Outputs:
  UploadApiEndpoint:
    Description: "EEG Upload API endpoint URL"
    Value: !Sub "https://${SharedApiId}.execute-api.${AWS::Region}.amazonaws.com/dev/api/upload"
