AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI4NG EEG Upload Lambda API (Manual API Integration)

Parameters:
  SharedApiId:
    Type: String
    Description: Existing API Gateway HTTP API ID

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: dotnet8

Resources:
  EEGUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ai4ngstore-dev
      VersioningConfiguration:
        Status: Enabled

  AI4NGUploadLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: AI4NGUploadLambda::AI4NGUploadLambda.Function::FunctionHandler
      CodeUri: ../src/AI4NGUploadLambda
      Environment:
        Variables:
          UPLOAD_BUCKET: !Ref EEGUploadBucket
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3WritePolicy:
            BucketName: !Ref EEGUploadBucket

  UploadIntegration:
    Type: AWS::ApiGatewayV2::Integration #handles linking the API Gateway to the Lambda function
    Properties:
      ApiId: !Ref SharedApiId
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AI4NGUploadLambda.Arn}/invocations
      PayloadFormatVersion: '2.0'
      IntegrationMethod: POST

  UploadRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SharedApiId
      RouteKey: GET /api/upload #route for uploading EEG data
      AuthorizationType: JWT
      AuthorizerId: !ImportValue SharedApiAuthorizerId
      Target: !Sub integrations/${UploadIntegration}

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AI4NGUploadLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${SharedApiId}/*/GET/api/upload

Outputs:
  UploadApiEndpoint:
    Description: EEG Upload API endpoint URL
    Value: !Sub https://${SharedApiId}.execute-api.${AWS::Region}.amazonaws.com/dev/api/upload