AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI4NG EEG Upload Lambda API

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: dotnet8

  Api:
    Name: AI4NG-dev
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"

Resources:
  # S3 Bucket
  EEGUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ai4ngstore-dev
      VersioningConfiguration:
        Status: Enabled

  # Lambda Function: EEG Upload
  AI4NGUploadLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: AI4NGUploadLambda::AI4NGUploadLambda.Function::FunctionHandler
      CodeUri: ../src/AI4NGUploadLambda
      Environment:
        Variables:
          UPLOAD_BUCKET: !Ref EEGUploadBucket
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3WritePolicy:
            BucketName: !Ref EEGUploadBucket
      Events:
        GeneratePresignedUrl:
          Type: HttpApi
          Properties:
            Path: /api/upload
            Method: GET
            ApiId: !ImportValue SharedApiId
            Auth:
              Authorizer: CognitoAuthorizer

Outputs:
  UploadApiEndpoint:
    Description: "EEG Upload API endpoint URL"
    Value: !Sub "https://${AI4NGHttpApi}.execute-api.${AWS::Region}.amazonaws.com/dev/api/upload"
