name: Deploy to AWS Lambda

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: eu-west-2

      - name: Get Shared API ID from CloudFormation export
        id: get_api_id
        run: |
          echo "Fetching Shared API ID..."
          API_ID=$(aws cloudformation list-exports \
            --query "Exports[?Name=='SharedApiId'].Value" \
            --output text)
          echo "api_id=$API_ID" >> $GITHUB_OUTPUT

      - name: Build SAM
        run: sam build --template-file infra/template.yaml

      - name: Deploy SAM
        run: |
          sam deploy \
            --parameter-overrides SharedApiId=${{ steps.get_api_id.outputs.api_id }} \
            --config-env default